//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientService
    {
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDService { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public string Comment { get; set; }
    }
}
